name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Voz - entrada y salida
  speech_to_text: ^6.6.0
  flutter_tts: ^4.0.2

  # Cámara y escáner
  camera: ^0.10.5
  mobile_scanner: ^5.1.0

  # Navegación entre pantallas
  go_router: ^13.2.0

  # Utilidades
  http: ^1.2.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/